# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.service.shop:
    class: 'AppBundle\Service\Basket'
    arguments: ["@=service('doctrine').getRepository('AppBundle:Basket')"]
  app.service.product:
      class: 'AppBundle\Service\Product'
      arguments: ["@=service('doctrine').getRepository('AppBundle:ProductRelationPackage')"]